
project_id = "mmbrvcndxhipaoxysvwr"

[functions]
max_request_size = "15mb"

[functions.is_admin]
verify_jwt = true

[functions.initialize-admin]
verify_jwt = false

[functions.reset-admin-password]
verify_jwt = false

[functions.create-new-admin]
verify_jwt = false

[functions.tailor-cv]
verify_jwt = false

[functions.process-cv-job]
verify_jwt = false
